### ISSUE TITLE
Your module 2 solution

### ISSUE THREAD

**Issue by spaiq** [vic-g/coursera-webdev#1]
Hey vic-g!
I'm gonna review your submission as a peer but have in mind that the solution should be linked from your github page, not the direct repository (documentation on how to do all this is here: https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site).
Have a good one buddy!

**Comment by vic-g** [comment]
Hey spaiq, than you for the heads-up! I'll get that fixed at my earliest convenience.
